---
#  - name: Activate Satellite repositories
#    rhsm_repository:
#      name: "{{ item }}"
#      state: enabled
#    with_items:
#      - rhel-server-rhscl-7-rpms
#    tags:
#      - skip

  - name: Install PostgreSQL
    yum:
      name: rh-postgresql10
      state: present

  - name: Install python psycopg2 module
    yum:
      name: python-psycopg2
      state: present

  - name: Unmount DB data volume from default location
    mount:
      path: "{{ default_db_disk_mount }}"
      src: "{{ db_disk_src }}"
      fstype: "{{ db_disk_fs_type }}"
      state: absent

#There has a bug, when changed PostgreSQL directory, the systemd target is still stayed at /opt directory, 
# restart machine need to change /usr/lib/systemd/system/rh-postgresql10-postgresql.service target
# because default ExecStartPre and ExecStart working environment is /opt/rh/rh-postgresql10/root/usr/, 
# this need change to /var/lib/pgsql/rh/rh-postgresql10/root/usr/
  - name: Mount /data volume to PostgreSQL directory
    mount:
      path: /var/lib/pgsql
      src: "{{ db_disk_src }}"
      fstype: "{{ db_disk_fs_type }}"
      state: present
